"""
export/markdown_writer.py — Generate comprehensive Markdown startup plan
"""
import json
from backend.context import RunContext


async def generate_markdown(ctx: RunContext) -> str:
    """Generate a complete Markdown startup plan from the RunContext."""
    idea = ctx.startup_idea
    market = ctx.market_research
    comp = ctx.competitor_analysis
    personas = ctx.customer_personas
    product = ctx.product_design
    roadmap = ctx.mvp_roadmap
    biz = ctx.business_model
    pricing = ctx.pricing_strategy
    fin = ctx.financial_projections
    risk = ctx.risk_register
    tech = ctx.tech_architecture
    db = ctx.database_schema
    security = ctx.security_compliance
    pitch = ctx.pitch_deck
    exec_sum = ctx.executive_summary

    lines = []

    # Header
    startup_name = idea.get("startup_name", "Our Startup")
    lines.append(f"# {startup_name} — AI-Generated Startup Plan")
    lines.append(f"> Generated by AI Startup Co-Founder Agent | Run ID: `{ctx.run_id}`")
    lines.append("")

    # Executive Summary
    lines.append("## 📋 Executive Summary")
    lines.append("")
    lines.append(exec_sum.get("executive_summary", ""))
    lines.append("")
    lines.append(f"**One-liner:** {exec_sum.get('one_liner', idea.get('one_liner', ''))}")
    lines.append(f"**Elevator Pitch:** {exec_sum.get('elevator_pitch', '')}")
    lines.append("")

    # Metrics Snapshot
    metrics = exec_sum.get("key_metrics_snapshot", {})
    if metrics:
        lines.append("### Key Metrics")
        for k, v in metrics.items():
            lines.append(f"- **{k.replace('_', ' ').title()}:** {v}")
        lines.append("")

    # Startup Idea
    lines.append("---")
    lines.append("## 💡 Startup Idea")
    lines.append(f"**Name:** {idea.get('startup_name', '')}")
    lines.append(f"**Tagline:** {idea.get('tagline', '')}")
    lines.append(f"**Value Proposition:** {idea.get('value_proposition', '')}")
    lines.append(f"**Target Customer:** {idea.get('target_customer', '')}")
    lines.append(f"**Key Differentiator:** {idea.get('key_differentiator', '')}")
    lines.append(f"**Unfair Advantage:** {idea.get('unfair_advantage', '')}")
    lines.append("")

    # Market Research
    lines.append("---")
    lines.append("## 📊 Market Research")
    lines.append(f"- **TAM:** ${market.get('tam_usd_billions', '?')}B")
    lines.append(f"- **SAM:** ${market.get('sam_usd_billions', '?')}B")
    lines.append(f"- **SOM:** ${market.get('som_usd_millions', '?')}M")
    lines.append(f"- **CAGR:** {market.get('cagr_percent', '?')}%")
    lines.append(f"- **Market Timing:** {market.get('market_timing', '')}")
    lines.append("")
    if market.get("market_trends"):
        lines.append("### Market Trends")
        for trend in market.get("market_trends", []):
            lines.append(f"- {trend}")
        lines.append("")

    # Competitors
    lines.append("---")
    lines.append("## 🥊 Competitive Landscape")
    competitors = comp.get("competitors", [])
    if competitors:
        lines.append("| Company | Funding | Price | Strengths | Weaknesses |")
        lines.append("|---------|---------|-------|-----------|------------|")
        for c in competitors:
            strengths = " / ".join(c.get("strengths", [])[:2])
            weaknesses = " / ".join(c.get("weaknesses", [])[:2])
            lines.append(f"| {c.get('name','?')} | {c.get('funding_stage','?')} | ${c.get('starting_price_monthly','?')}/mo | {strengths} | {weaknesses} |")
        lines.append("")
    if comp.get("market_gaps"):
        lines.append("### Market Gaps We Exploit")
        for gap in comp.get("market_gaps", []):
            lines.append(f"- {gap}")
        lines.append("")

    # Customer Personas
    lines.append("---")
    lines.append("## 👤 Customer Personas")
    for persona in personas:
        lines.append(f"### {persona.get('name', 'Persona')} — {persona.get('job_title', '')}")
        lines.append(f"**Age:** {persona.get('age', '?')} | **Location:** {persona.get('location', '?')} | **WTP:** ${persona.get('willingness_to_pay_monthly_usd', '?')}/mo")
        lines.append(f"*\"{persona.get('quote', '')}\"*")
        if persona.get("pain_points"):
            lines.append("**Pain Points:**")
            for pain in persona.get("pain_points", [])[:3]:
                lines.append(f"- {pain}")
        lines.append("")

    # Product Design
    lines.append("---")
    lines.append("## 🎨 Product Design")
    must_haves = product.get("must_have_features", [])
    if must_haves:
        lines.append("### Must-Have Features (P0)")
        for f in must_haves:
            lines.append(f"- **{f.get('feature', '?')}:** {f.get('description', '')}")
        lines.append("")
    flows = product.get("core_ux_flows", [])
    if flows:
        lines.append("### Core UX Flows")
        for flow in flows:
            lines.append(f"**{flow.get('flow_name', '?')}** (~{flow.get('estimated_completion_time', '?')})")
            for step in flow.get("steps", []):
                lines.append(f"  1. {step}")
        lines.append("")

    # Business Model
    lines.append("---")
    lines.append("## 💼 Business Model")
    revenue_streams = biz.get("revenue_streams", [])
    if revenue_streams:
        for stream in revenue_streams:
            lines.append(f"- **{stream.get('stream', '?')}** ({stream.get('model', '?')}): {stream.get('description', '')}")
    lines.append("")
    gtm_phases = biz.get("gtm_phases", [])
    if gtm_phases:
        lines.append("### Go-To-Market Phases")
        for phase in gtm_phases:
            lines.append(f"- **{phase.get('phase', '?')}:** {phase.get('strategy', '')} → {phase.get('target', '')}")
        lines.append("")

    # Pricing
    lines.append("---")
    lines.append("## 💰 Pricing Strategy")
    tiers = pricing.get("tiers", [])
    if tiers:
        lines.append("| Tier | Monthly | Annual | Target |")
        lines.append("|------|---------|--------|--------|")
        for tier in tiers:
            lines.append(f"| {tier.get('tier_name','?')} | ${tier.get('price_monthly_usd',0)}/mo | ${tier.get('price_annual_usd',0)}/yr | {tier.get('target_persona','?')} |")
        lines.append("")

    # Financial Projections
    lines.append("---")
    lines.append("## 📈 Financial Projections (12 Months)")
    lines.append(f"- **Break-even Month:** {fin.get('breakeven_month', '?')}")
    lines.append(f"- **12-Month ARR:** ${fin.get('arr_month_12_usd', 0):,}")
    lines.append(f"- **LTV:** ${fin.get('ltv_usd', 0):,}")
    lines.append(f"- **CAC:** ${fin.get('cac_usd', 0):,}")
    lines.append(f"- **LTV:CAC Ratio:** {fin.get('ltv_cac_ratio', 0):.1f}x")
    lines.append("")
    monthly = fin.get("monthly_projections", [])
    if monthly:
        lines.append("| Month | Customers | MRR | Net Profit |")
        lines.append("|-------|-----------|-----|-----------|")
        for m in monthly:
            lines.append(f"| {m.get('month','?')} | {m.get('total_customers',0):,} | ${m.get('mrr_usd',0):,} | ${m.get('net_profit_usd',0):,} |")
        lines.append("")

    # MVP Roadmap
    lines.append("---")
    lines.append("## 🗺️ MVP Roadmap")
    sprints = roadmap.get("sprints", [])
    for sprint in sprints:
        lines.append(f"### Sprint {sprint.get('sprint_number', '?')} — {sprint.get('theme', '')} ({sprint.get('duration_weeks', 2)} weeks)")
        lines.append(f"**Goal:** {sprint.get('sprint_goal', '')}")
        lines.append(f"**Deliverable:** {sprint.get('deliverable', '')}")
        stories = sprint.get("user_stories", [])
        if stories:
            lines.append("**User Stories:**")
            for story in stories[:3]:
                lines.append(f"- [{story.get('id','')}] {story.get('title', '')} ({story.get('story_points', '?')} pts)")
        lines.append("")

    # Tech Architecture
    lines.append("---")
    lines.append("## 🏗️ Tech Architecture")
    fe = tech.get("frontend_stack", {})
    be = tech.get("backend_stack", {})
    db_info = tech.get("database", {})
    ai = tech.get("ai_layer", {})
    lines.append(f"- **Frontend:** {fe.get('framework', '?')} + {fe.get('styling', '?')} → {fe.get('hosting', '?')}")
    lines.append(f"- **Backend:** {be.get('framework', '?')} ({be.get('language', '?')}) → {be.get('hosting', '?')}")
    lines.append(f"- **Database:** {db_info.get('primary', '?')}")
    lines.append(f"- **AI Layer:** {ai.get('primary_llm', '?')}")
    lines.append(f"- **Infra Cost:** ${tech.get('estimated_monthly_infra_cost_usd', 0)}/month")
    lines.append("")
    if tech.get("architecture_description"):
        lines.append(tech.get("architecture_description", ""))
        lines.append("")

    # Database Schema
    lines.append("---")
    lines.append("## 🗄️ Database Schema")
    lines.append("```sql")
    lines.append(db.get("sql_schema", "-- Schema not generated"))
    lines.append("```")
    lines.append("")

    # Security
    lines.append("---")
    lines.append("## 🔒 Security & Compliance")
    launch_checklist = security.get("security_launch_checklist", [])
    if launch_checklist:
        lines.append("### Launch Security Checklist")
        for item in launch_checklist:
            lines.append(f"- [ ] {item}")
        lines.append("")
    llm_safety = security.get("llm_safety_measures", [])
    if llm_safety:
        lines.append("### LLM Safety Measures")
        for item in llm_safety:
            lines.append(f"- {item}")
        lines.append("")

    # Risk Register
    lines.append("---")
    lines.append("## ⚠️ Risk Register")
    risks = risk.get("risks", [])
    if risks:
        lines.append("| # | Risk | Probability | Impact | Mitigation |")
        lines.append("|---|------|-------------|--------|------------|")
        for r in risks[:10]:
            lines.append(f"| {r.get('risk_id','?')} | {r.get('title','?')} | {r.get('probability','?')} | {r.get('impact','?')} | {r.get('mitigation_strategy', '')[:80]} |")
        lines.append("")

    # Pitch Deck
    lines.append("---")
    lines.append("## 🎯 Pitch Deck (12 Slides)")
    slides = pitch.get("slides", [])
    for slide in slides:
        lines.append(f"### Slide {slide.get('slide_number', '?')}: {slide.get('title', '')}")
        lines.append(f"**{slide.get('headline', '')}**")
        for bullet in slide.get("bullet_points", []):
            lines.append(f"- {bullet}")
        if slide.get("key_stat"):
            lines.append(f"**📊 Key Stat:** {slide.get('key_stat', '')}")
        lines.append(f"*Speaker Notes: {slide.get('speaker_notes', '')}*")
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by AI Startup Co-Founder Agent — {ctx.created_at.strftime('%Y-%m-%d %H:%M UTC')}*")

    return "\n".join(lines)
